### ISSUE TITLE
Saving the trimmed part of an audio

### ISSUE THREAD

**Issue by codename-samy** [lestercorreya/Audio-Editor#1]
Hey,
Its a great project I had just seen, but can you please let me know is there any option where you had worked for saving the trimmed part of the complete audio file.

**Comment by lestercorreya** [comment]
Hey,
Apologies for the late response as I couldn't check my mail regularly due
to college examinations. I haven't worked on saving the trimmed part of the
audio file yet as it wasn't mentioned in the project description, but this
functionality seems definitely possible.
May I also know from where you came across my project link?

**Comment by codename-samy** [comment]
Thanks for the reply,

I was working on a real time telephony concept, where I need to trim the audio file and save it for the further modification / usage.

Not a worry, I have figured out a decent approach for the downloading part of the audio after cropping them into smaller pieces. 

Please do check my OPENSRC Project ready for further development at; ----> https://github.com/codename-samy/Toice <-----

Again, thanks for your concern.
Have a nice day.

**Comment by codename-samy** [comment]
This downloading function can be achieved by using a Worker function, which reconstruct the crop file and produce user as a single segment, if requested by pressing Download button.
